site_name: Documentation Site - Saudi Arabian vACC
site_url: https://mydomain.org/mysite
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  font: 
    text: Mulish
  palette:
    scheme: slate
    primary: green
    accent: deep purple
  features:
    - navigation.footer